### ISSUE TITLE
Comments tablosu CRUD işlemleri

### ISSUE THREAD

**Issue by saracalihan** [mavidurak/orientation-api#3]
- [ ] Model oluşturulacak
- [ ] Migrasyon yazılacak
- [ ] Create işlemi
- [ ] Update işlemi
- [ ] Read işlemi
- [ ] Delete işlemi

Veritabanı şeması:
https://github.com/mavidurak/orientation-api/blob/main/docs/database_schema/db_schema.md

Kullanılacak end point'ler:
[docs/routes/comments](https://github.com/mavidurak/orientation-api/blob/main/docs/routes/routes.md#comments) içindeki `GET /users/:userId/comments/:id` ve `GET /users/:userId/comments` hariç tüm end pointler ve `GET /comments/:id`(request almayacak ve response olarak ilgili comment'in tüm bilgilerini dönecek)

`GET /comments/:id`  dışındaki tüm end pointler kullanıcı bilgisini header içinden gelen `x-access-token` sayesine `req.user` içinden alınmalı ve sadece comment sahibi olan kişi ilgili işlemi yapabilmelidir.

Hatalı işlemler için önürülecek cevap:
```js
{
  errors: [
    {
       message: "Comment not found or you don\'t have a permission!"
    }  
  ]
}
```

**User tablosu dışındaki tablolar ile olan bağlantılar önümüzdeki hafta yapılacaktır.**

**Comment by beyzaerkan** [comment]
https://github.com/mavidurak/orientation-api/pull/12
