### ISSUE TITLE
Review yapılırken spoiler butonu seçilmezse spoiler butonunun boolean olması gerekiğini konusunda hata veriyor

### ISSUE THREAD

**Issue by burakack** [mavidurak/orientation-api#52]
Bu buton seçilmediği zaman kullanıcı bir hata almamalıdır. Bu durumlarda "False" olmalıdır.

**Comment by saracalihan** [comment]
@burakack bu iş Frontend içinde yapılması gerektiği için issue'yu kapatıyorum. Bildirin için teşekkürler.
