### ISSUE TITLE
Wanted Contents tablosu CRUD işlemleri

### ISSUE THREAD

**Issue by saracalihan** [mavidurak/orientation-api#8]
- [ ] Modeli oluşturulacak
- [ ] Migrasyon yazılacak
- [ ] Create işlemi
- [ ] Update işlemi
- [ ] Read işlemi
- [ ] Delete işlemi

Veritabanı şeması:
https://github.com/mavidurak/orientation-api/blob/main/docs/database_schema/db_schema.md

Kullanılacak end point'ler:
[docs/routes/wanted-lists](https://github.com/mavidurak/orientation-api/blob/main/docs/routes/routes.md#wanted-lists) içindeki  [GET /communities/:communityId/discussions](https://github.com/mavidurak/orientation-api/blob/main/docs/routes/routes.md#get-usersuseridwanted-lists) haricindeki tüm end pointler

Tüm end pointler kullanıcı bilgisi header içinden gelen `x-access-token` sayesine `req.user` içinden alınmalı ve sadece kullanıcı kendine ait `wanted_content`'ler için işlem yapabilmelidir.Kullanıcıya ait tüm `wanted_content`'ler bir araya gelerek `wanted_list`'i yazılımsal olarak oluşturur.

Hatalı işlemler için önürülecek cevap:
```js
{
  errors: [
    {
       message: "Wanted content not found or you don\'t have a permission!"
    }  
  ]
}
```

**Comment by burakack** [comment]
model oluşturuldu.
migrasyon oluşturuldu.

**Comment by burakack** [comment]
Create Read Update Delete işlemleri oluşturuldu
